#include "AEEStdDef.idl"
#include "remote.idl"

const string IDL_VERSION = "0.0.2";

interface ggml_htp : remote_handle64 {
   AEEResult setclocks(in int32 diag_info, in int32 requested_thread_counts, rout int32 actual_thread_counts);
   AEEResult register_rpcmem(in uint32 ion_fd, in uint32 size_lo, in uint32 size_hi);
   AEEResult execute_batch(in uint32 batch_offset, in uint32 batch_size);
};
